Repository snowplow/snowplow-javascript-tracker, pull requests merged in 2022-09, with the labels that each got.

#1084 Update tracker core docs to 3.6.0
  common/changes/@snowplow/tracker-core/master_2022-09-08-12-18.json
  libraries/tracker-core/README.md
Labels: cla:yes

#1092 Update insecure terser version (Fixes #1091)
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
Labels: category:dependencies

#1094 Update rush version, upgrade Node.js GA action version, remove Node 12 (closes #1093)
  .github/workflows/build.yml
  .github/workflows/change_check.yml
  .github/workflows/publish.yml
  .github/workflows/publish_prerelease.yml
  .github/workflows/snyk.yml
  .nvmrc
  README.md
  common/changes/@snowplow/browser-plugin-ad-tracking/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-browser-features/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-client-hints/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-consent/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-debugger/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-ecommerce/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-enhanced-ecommerce/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-error-tracking/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-form-tracking/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-ga-cookies/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-geolocation/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-link-click-tracking/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-media-tracking/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-optimizely-x/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-optimizely/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-performance-timing/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-site-tracking/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-timezone/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-plugin-youtube-tracking/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-tracker-core/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/browser-tracker/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/javascript-tracker/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/node-tracker/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/changes/@snowplow/tracker-core/feature-1093-update-rush-upgrade-node_2022-08-29-12-10.json
  common/scripts/install-run-rush.js
  common/scripts/install-run.js
  libraries/browser-tracker-core/README.md
  libraries/tracker-core/README.md
  plugins/browser-plugin-ad-tracking/README.md
  plugins/browser-plugin-browser-features/README.md
  plugins/browser-plugin-client-hints/README.md
  plugins/browser-plugin-consent/README.md
  plugins/browser-plugin-debugger/README.md
  plugins/browser-plugin-ecommerce/README.md
  plugins/browser-plugin-enhanced-ecommerce/README.md
  plugins/browser-plugin-error-tracking/README.md
  plugins/browser-plugin-form-tracking/README.md
  plugins/browser-plugin-ga-cookies/README.md
  plugins/browser-plugin-geolocation/README.md
  plugins/browser-plugin-link-click-tracking/README.md
  plugins/browser-plugin-media-tracking/README.md
  plugins/browser-plugin-optimizely-x/README.md
  plugins/browser-plugin-optimizely/README.md
  plugins/browser-plugin-performance-timing/README.md
  plugins/browser-plugin-site-tracking/README.md
  plugins/browser-plugin-timezone/README.md
  plugins/browser-plugin-youtube-tracking/README.md
  rush.json
  trackers/browser-tracker/README.md
  trackers/javascript-tracker/README.md
  trackers/node-tracker/README.md
Labels: category:setup

#1097 Remove unused python server file (closes #961)
  common/changes/@snowplow/javascript-tracker/issue-961-remove-unused-python-script_2022-08-30-10-08.json
  trackers/javascript-tracker/test/local/http-server.py
Labels: category:setup

#1099 Add tests to verify Node.js tracker returns eid (event id) attribute (closes #1098)
  common/changes/@snowplow/node-tracker/feature-1098-verify-eid-returned-node-track_2022-08-31-10-09.json
  common/changes/@snowplow/tracker-core/feature-1098-verify-eid-returned-node-track_2022-08-31-10-09.json
  libraries/tracker-core/test/core.ts
  trackers/node-tracker/test/tracker.ts
Labels: category:testing

#1102 Add bundlemon and first size limits on distributables (closes #1083)
  .bundlemonrc.json
  .github/workflows/change_check.yml
Labels: category:setup

#1096 Update got version to 11.8.5 (fixes #1095)
  common/changes/@snowplow/node-tracker/issue-1095-fix-node-got-vulnerable-version_2022-08-29-14-31.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  trackers/node-tracker/package.json
Labels: category:dependencies

#1108 Correct initial session_index value and after clearUserData() (closes #1106 #1107)
  common/changes/@snowplow/browser-tracker-core/issue-1106-1107-domain-session-index-fixes_2022-09-06-15-17.json
  libraries/browser-tracker-core/src/tracker/index.ts
  libraries/browser-tracker-core/test/helpers/index.ts
  libraries/browser-tracker-core/test/tracker/session_data.test.ts
Labels: type:defect
